baseURL: "https://lenka98.github.io/" 
title: Manoj Kumar Lenka
paginate: 10
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: /papers/
          weight: 1

params:
    description: "Manoj Kumar Lenka is a MS student at the Indian Institute of Technology Madras. He works in SENSE Lab, mainly focusing on wireless sensing and TinyML"
    author: Manoj Kumar Lenka
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Manoj Kumar Lenka
          subtitle: "I'm a MS student in the Department of Computer Science and Engineering at the Indian Institute of Technology Madras, Chennai. I am engaged in resarch at SENSE Lab under the guidance of Dr. Ayon Chakraborty. My research focus spans the interdisciplinary domains of sensing, wireless communication, embedded systems, and machine learning "
          imageUrl: "/picture.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Manoj Kumar Lenka
          buttons:
            - name: Publications
              url: /papers/

    socialIcons:
        - name: CV
          url: /cv.pdf
        - name: Email
          url: mailto:manojlenka1998@gmail.com
        - name: Location
          url: /location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=c_jUvRkAAAAJ
        - name: GitHub
          url: https://github.com/lenka98

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Manoj Kumar Lenka"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
